//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoranUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public int Musteri_id { get; set; }
        public string Musteri_Adi { get; set; }
    }
}
